main: main.cpp AbstractPriorityQueue.h UnsortedPriorityQueue.h SortedPriorityQueue.h PriorityQueueHeap.h
	g++ -std=c++17 main.cpp -o main

pq_test: pq_test.cpp AbstractPriorityQueue.h UnsortedPriorityQueue.h SortedPriorityQueue.h PriorityQueueHeap.h
	g++ -std=c++17 pq_test.cpp -o pq_test