main: main.cpp sort.cpp SortedPriorityQueue.h
	g++ -std=c++17 main.cpp -o main

test_sort: sort.cpp SortedPriorityQueue.h test_sort.cpp
	g++ -std=c++17 test_sort.cpp -o test_sort

pq_test: pq_test.cpp AbstractPriorityQueue.h SortedPriorityQueue.h
	g++ -std=c++17 pq_test.cpp -o pq_test