main: main.cpp AbstractStack.h StackArrayDouble.h StackArrayLinear.h StackLinkedList.h
	g++ -std=c++11 main.cpp -o main

stack_test: stack_test.cpp AbstractStack.h StackArrayDouble.h StackArrayLinear.h StackLinkedList.h
	g++ -std=c++11 stack_test.cpp -o ./stack_test
